# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datanum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datanum.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rdatanum.proto\"B\n\x07\x44\x61taNum\x12\x0f\n\x07mixture\x18\x01 \x01(\x0c\x12\x0e\n\x06vocals\x18\x02 \x01(\x0c\x12\x16\n\x0evocals_indices\x18\x03 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATANUM = _descriptor.Descriptor(
  name='DataNum',
  full_name='DataNum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mixture', full_name='DataNum.mixture', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vocals', full_name='DataNum.vocals', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vocals_indices', full_name='DataNum.vocals_indices', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['DataNum'] = _DATANUM

DataNum = _reflection.GeneratedProtocolMessageType('DataNum', (_message.Message,), dict(
  DESCRIPTOR = _DATANUM,
  __module__ = 'datanum_pb2'
  # @@protoc_insertion_point(class_scope:DataNum)
  ))
_sym_db.RegisterMessage(DataNum)


# @@protoc_insertion_point(module_scope)
